services:
  kasm-db:
    container_name: kasm-db
    image: dind-ubuntu:latest
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - kasm-network
    volumes:
      - ./db-opt:/opt/kasm
      - ./db-postgresql:/var/lib/postgresql
      - ./db-docker-data:/var/lib/docker
    ports:
      - "5432:5432"

  kasm-manager:
    container_name: kasm-manager
    image: dind-ubuntu:latest
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - kasm-network
    volumes:
      - ./manager-opt:/opt/kasm
      - ./manager-docker-data:/var/lib/docker
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - kasm-db

networks:
  kasm-network:
    driver: bridge